[shopee]
csv_default=sheet.csv
expected_keys=id,name,price,url
json_path=.

[lazada]
csv_default=lazada.csv
expected_keys=id,name,price,link
json_path=.products[]

[temu]
csv_default=temu.csv
expected_keys=id,name,price,url
json_path=.
