// 所有历史数据 - 自动生成 $(date '+%Y-%m-%d %H:%M:%S')
window.allHistoryData = {
  // 2026-01-26
  '20260126': {
    date: '20260126',
    display: '2026-01-26',
    file: 'history/picks_20260126.json',
    data: 
      {
        "date": "2026-01-26",
        "date_id": "20260126",
        "last_updated": "2026-02-01 23:13:12",
        "source": "20260126.csv",
        "total_picks": 15,
        "sector_breakdown": {
          "Technology": 12,
          "Property": 1,
          "Industrial & Consumer Products": 2
        },
        "picks": [
          {
            "rank": 1,
            "code": "5031C6",
            "name": "TIMECOM-C6",
            "instrument_type": "Warrant",
            "sector": "363",
            "sector_name": "Technology",
            "current_price": 0.215,
            "daily_change": 2.58,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 0,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 2,
            "code": "0255WA",
            "name": "EIB-WA",
            "instrument_type": "Warrant",
            "sector": "402",
            "sector_name": "Property",
            "current_price": 0.015,
            "daily_change": 2.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 2039850,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 3,
            "code": "659944",
            "name": "AEON-C44",
            "instrument_type": "Warrant",
            "sector": "301",
            "sector_name": "Technology",
            "current_price": 0.025,
            "daily_change": 1.5,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 274230,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 4,
            "code": "523829",
            "name": "AAX-C29",
            "instrument_type": "Warrant",
            "sector": "301",
            "sector_name": "Technology",
            "current_price": 0.2,
            "daily_change": 1.5,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 339665,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 5,
            "code": "0043",
            "name": "MTRONIC",
            "instrument_type": "Stock",
            "sector": "102",
            "sector_name": "Industrial & Consumer Products",
            "current_price": 0.01,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 1057535,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 6,
            "code": "86641A",
            "name": "SPSETIA-C1A",
            "instrument_type": "Stock",
            "sector": "320",
            "sector_name": "Technology",
            "current_price": 0.01,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 681990,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 7,
            "code": "33361J",
            "name": "IJM-C1J",
            "instrument_type": "Stock",
            "sector": "303",
            "sector_name": "Technology",
            "current_price": 0.01,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 2714700,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 8,
            "code": "86641B",
            "name": "SPSETIA-C1B",
            "instrument_type": "Stock",
            "sector": "320",
            "sector_name": "Technology",
            "current_price": 0.02,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 336460,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 9,
            "code": "523832",
            "name": "AAX-C32",
            "instrument_type": "Warrant",
            "sector": "301",
            "sector_name": "Technology",
            "current_price": 0.355,
            "daily_change": 0.73,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 2915375,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 10,
            "code": "523830",
            "name": "AAX-C30",
            "instrument_type": "Warrant",
            "sector": "301",
            "sector_name": "Technology",
            "current_price": 0.125,
            "daily_change": 0.67,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 1817605,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 11,
            "code": "523831",
            "name": "AAX-C31",
            "instrument_type": "Warrant",
            "sector": "301",
            "sector_name": "Technology",
            "current_price": 0.185,
            "daily_change": 0.61,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 1415665,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 12,
            "code": "33361L",
            "name": "IJM-C1L",
            "instrument_type": "Stock",
            "sector": "303",
            "sector_name": "Technology",
            "current_price": 0.04,
            "daily_change": 0.6,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 891520,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 13,
            "code": "659946",
            "name": "AEON-C46",
            "instrument_type": "Warrant",
            "sector": "301",
            "sector_name": "Technology",
            "current_price": 0.04,
            "daily_change": 0.6,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 0,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 14,
            "code": "0744C1",
            "name": "AMD-C1",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.135,
            "daily_change": 0.59,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 55775,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 15,
            "code": "7097",
            "name": "TAWIN",
            "instrument_type": "Stock",
            "sector": "102",
            "sector_name": "Industrial & Consumer Products",
            "current_price": 0.015,
            "daily_change": 0.5,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 1058875,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          }
        ]
      }  },
  // 2026-01-27
  '20260127': {
    date: '20260127',
    display: '2026-01-27',
    file: 'history/picks_20260127.json',
    data: 
      {
        "date": "2026-01-27",
        "date_id": "20260127",
        "last_updated": "2026-02-01 23:13:32",
        "source": "20260127.csv",
        "total_picks": 15,
        "sector_breakdown": {
          "Technology": 12,
          "Property": 2,
          "Industrial & Consumer Products": 1
        },
        "picks": [
          {
            "rank": 1,
            "code": "0652K8",
            "name": "HSI-CWK8",
            "instrument_type": "Stock",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.02,
            "daily_change": 3.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 511715,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 2,
            "code": "530618",
            "name": "FFB-C18",
            "instrument_type": "Warrant",
            "sector": "301",
            "sector_name": "Technology",
            "current_price": 0.355,
            "daily_change": 1.09,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 185440,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 3,
            "code": "0094",
            "name": "ZENTECH",
            "instrument_type": "Stock",
            "sector": "405",
            "sector_name": "Property",
            "current_price": 0.01,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 774600,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 4,
            "code": "0652MQ",
            "name": "HSI-CWMQ",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.01,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 18972650,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 5,
            "code": "51481X",
            "name": "UEMS-C1X",
            "instrument_type": "Stock",
            "sector": "320",
            "sector_name": "Technology",
            "current_price": 0.01,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 433065,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 6,
            "code": "3379WC",
            "name": "INSAS-WC",
            "instrument_type": "Warrant",
            "sector": "110",
            "sector_name": "Industrial & Consumer Products",
            "current_price": 0.01,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 12649315,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 7,
            "code": "0116",
            "name": "FOCUS",
            "instrument_type": "Stock",
            "sector": "401",
            "sector_name": "Property",
            "current_price": 0.01,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 2855110,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 8,
            "code": "5336CH",
            "name": "CKI-CH",
            "instrument_type": "Warrant",
            "sector": "301",
            "sector_name": "Technology",
            "current_price": 0.02,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 0,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 9,
            "code": "521149",
            "name": "SUNWAY-C49",
            "instrument_type": "Warrant",
            "sector": "302",
            "sector_name": "Technology",
            "current_price": 0.045,
            "daily_change": 0.8,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 71145,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 10,
            "code": "12951Z",
            "name": "PBBANK-C1Z",
            "instrument_type": "Stock",
            "sector": "310",
            "sector_name": "Technology",
            "current_price": 0.035,
            "daily_change": 0.75,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 0,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 11,
            "code": "528851",
            "name": "SIMEPROP-C51",
            "instrument_type": "Warrant",
            "sector": "320",
            "sector_name": "Technology",
            "current_price": 0.04,
            "daily_change": 0.6,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 0,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 12,
            "code": "568114",
            "name": "PETDAG-C14",
            "instrument_type": "Warrant",
            "sector": "301",
            "sector_name": "Technology",
            "current_price": 0.015,
            "daily_change": 0.5,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 279660,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 13,
            "code": "16193Y",
            "name": "DRBHCOMC3Y",
            "instrument_type": "Stock",
            "sector": "301",
            "sector_name": "Technology",
            "current_price": 0.03,
            "daily_change": 0.5,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 182435,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 14,
            "code": "659941",
            "name": "AEON-C41",
            "instrument_type": "Warrant",
            "sector": "301",
            "sector_name": "Technology",
            "current_price": 0.015,
            "daily_change": 0.5,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 961095,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 15,
            "code": "4677HG",
            "name": "YTL-HG",
            "instrument_type": "Warrant",
            "sector": "365",
            "sector_name": "Technology",
            "current_price": 0.015,
            "daily_change": 0.5,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 733800,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          }
        ]
      }  },
  // 2026-01-28
  '20260128': {
    date: '20260128',
    display: '2026-01-28',
    file: 'history/picks_20260128.json',
    data: 
      {
        "date": "2026-01-28",
        "date_id": "20260128",
        "last_updated": "2026-02-01 23:13:42",
        "source": "20260128.csv",
        "total_picks": 15,
        "sector_breakdown": {
          "Technology": 13,
          "Industrial & Consumer Products": 2
        },
        "picks": [
          {
            "rank": 1,
            "code": "0650RE",
            "name": "FBMKLCI-CRE",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.23,
            "daily_change": 1.71,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 0,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 2,
            "code": "0652MD",
            "name": "HSI-CWMD",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.21,
            "daily_change": 1.0,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 13970,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 3,
            "code": "0118WD",
            "name": "TRIVE-WD",
            "instrument_type": "Warrant",
            "sector": "161",
            "sector_name": "Industrial & Consumer Products",
            "current_price": 0.01,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 328580,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 4,
            "code": "51683C",
            "name": "HARTA-C3C",
            "instrument_type": "Warrant",
            "sector": "362",
            "sector_name": "Technology",
            "current_price": 0.025,
            "daily_change": 0.67,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 920345,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 5,
            "code": "0652MV",
            "name": "HSI-CWMV",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.1,
            "daily_change": 0.67,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 13457690,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 6,
            "code": "0652MG",
            "name": "HSI-CWMG",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.26,
            "daily_change": 0.58,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 0,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 7,
            "code": "51683H",
            "name": "HARTA-C3H",
            "instrument_type": "Stock",
            "sector": "362",
            "sector_name": "Technology",
            "current_price": 0.055,
            "daily_change": 0.57,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 0,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 8,
            "code": "0652M7",
            "name": "HSI-CWM7",
            "instrument_type": "Stock",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.375,
            "daily_change": 0.53,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 30459410,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 9,
            "code": "51683D",
            "name": "HARTA-C3D",
            "instrument_type": "Stock",
            "sector": "362",
            "sector_name": "Technology",
            "current_price": 0.015,
            "daily_change": 0.5,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 168490,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 10,
            "code": "0652ML",
            "name": "HSI-CWML",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.18,
            "daily_change": 0.5,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 55686950,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 11,
            "code": "7219PA",
            "name": "AIZO-PA",
            "instrument_type": "Warrant",
            "sector": "102",
            "sector_name": "Industrial & Consumer Products",
            "current_price": 0.015,
            "daily_change": 0.5,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 2456975,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 12,
            "code": "6139C2",
            "name": "TAKAFUL-C2",
            "instrument_type": "Warrant",
            "sector": "310",
            "sector_name": "Technology",
            "current_price": 0.015,
            "daily_change": 0.5,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 639915,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 13,
            "code": "0652K5",
            "name": "HSI-CWK5",
            "instrument_type": "Stock",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.145,
            "daily_change": 0.45,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 58550,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 14,
            "code": "18181D",
            "name": "BURSA-C1D",
            "instrument_type": "Stock",
            "sector": "310",
            "sector_name": "Technology",
            "current_price": 0.13,
            "daily_change": 0.44,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 0,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 15,
            "code": "0652MC",
            "name": "HSI-CWMC",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.62,
            "daily_change": 0.44,
            "score": 88,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 185685,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          }
        ]
      }  },
  // 2026-01-29
  '20260129': {
    date: '20260129',
    display: '2026-01-29',
    file: 'history/picks_20260129.json',
    data: 
      {
        "date": "2026-01-29",
        "date_id": "20260129",
        "last_updated": "2026-02-01 23:13:54",
        "source": "20260129.csv",
        "total_picks": 15,
        "sector_breakdown": {
          "Technology": 10,
          "Industrial & Consumer Products": 4,
          "Property": 1
        },
        "picks": [
          {
            "rank": 1,
            "code": "058720",
            "name": "KUAISHO-C20",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.04,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 3164570,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 2,
            "code": "0650EH",
            "name": "FBMKLCI-HEH",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.02,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 425230,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 3,
            "code": "0650EI",
            "name": "FBMKLCI-HEI",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.01,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 239850,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 4,
            "code": "0041",
            "name": "HONGSENG",
            "instrument_type": "Stock",
            "sector": "105",
            "sector_name": "Industrial & Consumer Products",
            "current_price": 0.01,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 904670,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 5,
            "code": "71065G",
            "name": "SUPERMX-C5G",
            "instrument_type": "Stock",
            "sector": "362",
            "sector_name": "Technology",
            "current_price": 0.01,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 399550,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 6,
            "code": "058140",
            "name": "XIAOMI-C40",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.025,
            "daily_change": 0.67,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 916675,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 7,
            "code": "0207WA",
            "name": "MESTRON-WA",
            "instrument_type": "Warrant",
            "sector": "102",
            "sector_name": "Industrial & Consumer Products",
            "current_price": 0.015,
            "daily_change": 0.5,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 765205,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 8,
            "code": "7097",
            "name": "TAWIN",
            "instrument_type": "Stock",
            "sector": "102",
            "sector_name": "Industrial & Consumer Products",
            "current_price": 0.015,
            "daily_change": 0.5,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 1152940,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 9,
            "code": "0162",
            "name": "WIDAD",
            "instrument_type": "Stock",
            "sector": "403",
            "sector_name": "Property",
            "current_price": 0.015,
            "daily_change": 0.5,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 297315,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 10,
            "code": "0660AF",
            "name": "HSCEI-CAF",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.35,
            "daily_change": 0.46,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 0,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 11,
            "code": "0650EK",
            "name": "FBMKLCI-HEK",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.05,
            "daily_change": 0.43,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 534000,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 12,
            "code": "7198WC",
            "name": "DPS-WC",
            "instrument_type": "Warrant",
            "sector": "120",
            "sector_name": "Industrial & Consumer Products",
            "current_price": 0.02,
            "daily_change": 0.33,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 166375,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 13,
            "code": "0650EG",
            "name": "FBMKLCI-HEG",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.02,
            "daily_change": 0.33,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 0,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 14,
            "code": "522560",
            "name": "IHH-C60",
            "instrument_type": "Warrant",
            "sector": "362",
            "sector_name": "Technology",
            "current_price": 0.1,
            "daily_change": 0.33,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 170115,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 15,
            "code": "0652OD",
            "name": "HSI-CWOD",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.21,
            "daily_change": 0.31,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 0,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          }
        ]
      }  },
  // 2026-01-30
  '20260130': {
    date: '20260130',
    display: '2026-01-30',
    file: 'history/picks_20260130.json',
    data: 
      {
        "date": "2026-01-30",
        "date_id": "20260130",
        "last_updated": "2026-02-01 23:14:05",
        "source": "20260130.csv",
        "total_picks": 15,
        "sector_breakdown": {
          "Industrial & Consumer Products": 5,
          "Technology": 9,
          "Property": 1
        },
        "picks": [
          {
            "rank": 1,
            "code": "0043",
            "name": "MTRONIC",
            "instrument_type": "Stock",
            "sector": "102",
            "sector_name": "Industrial & Consumer Products",
            "current_price": 0.01,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 1056040,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 2,
            "code": "519985",
            "name": "HIBISCS-C85",
            "instrument_type": "Warrant",
            "sector": "361",
            "sector_name": "Technology",
            "current_price": 0.01,
            "daily_change": 1.0,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 349710,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 3,
            "code": "7018",
            "name": "CME",
            "instrument_type": "Stock",
            "sector": "102",
            "sector_name": "Industrial & Consumer Products",
            "current_price": 0.015,
            "daily_change": 0.5,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 111580,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 4,
            "code": "5085WB",
            "name": "MUDAJYA-WB",
            "instrument_type": "Warrant",
            "sector": "103",
            "sector_name": "Industrial & Consumer Products",
            "current_price": 0.075,
            "daily_change": 0.5,
            "score": 94,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 143350,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 5,
            "code": "519987",
            "name": "HIBISCS-C87",
            "instrument_type": "Warrant",
            "sector": "361",
            "sector_name": "Technology",
            "current_price": 0.09,
            "daily_change": 0.38,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 134880,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 6,
            "code": "0652NQ",
            "name": "HSI-PWNQ",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.075,
            "daily_change": 0.36,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 0,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 7,
            "code": "5293WA",
            "name": "AME-WA",
            "instrument_type": "Warrant",
            "sector": "103",
            "sector_name": "Industrial & Consumer Products",
            "current_price": 0.02,
            "daily_change": 0.33,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 153085,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 8,
            "code": "526351",
            "name": "SUNCON-C51",
            "instrument_type": "Warrant",
            "sector": "303",
            "sector_name": "Technology",
            "current_price": 0.02,
            "daily_change": 0.33,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 234025,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 9,
            "code": "0652NE",
            "name": "HSI-PWNE",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.08,
            "daily_change": 0.33,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 93365,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 10,
            "code": "0215CS",
            "name": "SLVEST-CS",
            "instrument_type": "Warrant",
            "sector": "361",
            "sector_name": "Technology",
            "current_price": 0.04,
            "daily_change": 0.33,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 1001275,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 11,
            "code": "0007",
            "name": "PUC",
            "instrument_type": "Stock",
            "sector": "463",
            "sector_name": "Property",
            "current_price": 0.02,
            "daily_change": 0.33,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 631175,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 12,
            "code": "0215CX",
            "name": "SLVEST-CX",
            "instrument_type": "Warrant",
            "sector": "361",
            "sector_name": "Technology",
            "current_price": 0.02,
            "daily_change": 0.33,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 2185015,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 13,
            "code": "6742HH",
            "name": "YTLPOWR-HH",
            "instrument_type": "Warrant",
            "sector": "365",
            "sector_name": "Technology",
            "current_price": 0.02,
            "daily_change": 0.33,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 307165,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 14,
            "code": "0743C1",
            "name": "CATL-C1",
            "instrument_type": "Warrant",
            "sector": "358",
            "sector_name": "Technology",
            "current_price": 0.2,
            "daily_change": 0.33,
            "score": 91,
            "potential_score": 95,
            "potential_reasons": "Warrant技術面向好，上漲潛力大",
            "recommendation": "🔥強烈買入（Warrant）",
            "risk_level": "高",
            "rsi": 50.0,
            "volume": 2909560,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          },
          {
            "rank": 15,
            "code": "7221",
            "name": "BSLCORP",
            "instrument_type": "Stock",
            "sector": "102",
            "sector_name": "Industrial & Consumer Products",
            "current_price": 0.02,
            "daily_change": 0.33,
            "score": 95,
            "potential_score": 95,
            "potential_reasons": "股價穩定，有上升潛力",
            "recommendation": "🔥強烈買入",
            "risk_level": "低",
            "rsi": 50.0,
            "volume": 1059415,
            "status": "中性",
            "pe_ratio": null,
            "dividend_yield": null,
            "macd": 0.0,
            "volume_ratio": 1.0
          }
        ]
      }  },
};

// 获取所有日期
window.getAllHistoryDates = function() {
    return Object.keys(window.allHistoryData);
};

// 获取特定日期的数据
window.getHistoryData = function(dateId) {
    return window.allHistoryData[dateId];
};

// 获取最新历史数据
window.getLatestHistoryData = function() {
    const dates = Object.keys(window.allHistoryData);
    if (dates.length === 0) return null;
    const latestDate = dates.sort().pop();
    return window.allHistoryData[latestDate];
};

// 检查是否在GitHub Pages环境
window.isGitHubPages = window.location.hostname.includes('github.io');

// 智能加载历史数据
window.loadHistoryDataSmart = function(dateId) {
    if (!dateId) {
        // 如果没有指定日期，使用最新日期
        const dates = Object.keys(window.allHistoryData);
        if (dates.length === 0) return null;
        dateId = dates.sort().pop();
    }
    
    if (window.isGitHubPages) {
        // GitHub Pages: 从内存加载
        if (window.allHistoryData && window.allHistoryData[dateId]) {
            return Promise.resolve(window.allHistoryData[dateId].data);
        }
    } else {
        // 本地环境: 从文件加载
        return fetch(`history/picks_${dateId}.json`)
            .then(response => {
                if (!response.ok) throw new Error('加载失败');
                return response.json();
            })
            .catch(error => {
                console.error('加载失败:', error);
                // 尝试从内存加载
                if (window.allHistoryData && window.allHistoryData[dateId]) {
                    return window.allHistoryData[dateId].data;
                }
                throw error;
            });
    }
    
    return Promise.reject(new Error('数据未找到'));
};
